import test,{before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { build } from 'esbuild';
import { mkdtemp,readFile,readdir,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { businessDate } from '../lib/domain.ts';
let dir,sql,api={},now=businessDate();
const context={DB:null,BUCKET:{put:async()=>{},get:async()=>null,delete:async()=>{}},who:{id:'owner',email:'owner@example.test',name:'Owner'}};
globalThis.__saathiTest=context;
class Statement{constructor(query,args=[]){this.query=query;this.args=args;}bind(...args){return new Statement(this.query,args);}async first(column){const value=sql.prepare(this.query).get(...this.args)??null;return column&&value?value[column]:value;}async all(){return {results:sql.prepare(this.query).all(...this.args),success:true,meta:{changes:0}};}async run(){const result=sql.prepare(this.query).run(...this.args);return {success:true,results:[],meta:{changes:Number(result.changes),last_row_id:Number(result.lastInsertRowid)}};}}
function adapter(){return {prepare:q=>new Statement(q),batch:async statements=>{sql.exec('BEGIN');try{const result=[];for(const s of statements){if(/^\s*SELECT/.test(s.query))result.push(await s.all());else result.push(await s.run());}sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
before(async()=>{dir=await mkdtemp(join(tmpdir(),'saathi-api-tests-'));for(const route of ['setup','state','workers','sites','attendance','payments','reversals','members','photos']){const outfile=join(dir,route+'.mjs');await build({entryPoints:['app/api/'+route+'/route.ts'],outfile,bundle:true,platform:'node',format:'esm',target:'node24',logLevel:'silent',plugins:[{name:'runtime-test-adapter',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'runtime',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'headers',namespace:'mock'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},args=>({loader:'js',contents:args.path==='runtime'?'export const env=globalThis.__saathiTest;':args.path==='headers'?`export async function headers(){const w=globalThis.__saathiTest.who;return new Headers(w?{'oai-authenticated-user-id':w.id}:{});}`:`export async function getChatGPTUser(){const w=globalThis.__saathiTest.who;return w?{email:w.email,displayName:w.name}:null;}`}));}}]});api[route]=await import(pathToFileURL(outfile));}});
after(async()=>{sql?.close();await rm(dir,{recursive:true,force:true});delete globalThis.__saathiTest;});
beforeEach(async()=>{sql?.close();sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+name,'utf8'));context.DB=adapter();context.who={id:'owner',email:'owner@example.test',name:'Owner'};});
async function call(route,payload,extra={}){const response=await api[route].POST(new Request('https://app.example.test/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',origin:'https://app.example.test',...extra},body:JSON.stringify(payload??{})}));return {status:response.status,data:await response.json()};}
async function setup(){const res=await call('setup');assert.equal(res.status,200,JSON.stringify(res.data));}
const op=(payload)=>({scope:'demo',operationId:crypto.randomUUID(),...payload});
const pay=()=>op({workerId:'demo-worker-0',amount:50000,kind:'advance',date:now,method:'cash',notes:''});
test('anonymous and unapproved accounts cannot read payroll',async()=>{context.who=null;let r=await api.state.GET(new Request('https://app.example.test/api/state'));assert.equal(r.status,401);context.who={id:'owner',email:'owner@example.test',name:'Owner'};await setup();context.who={id:'other',email:'other@example.test',name:'Other'};r=await api.state.GET(new Request('https://app.example.test/api/state'));assert.equal(r.status,403);});
test('setup creates a complete sample and leaves the real workspace empty',async()=>{await setup();await setup();assert.equal(sql.prepare("SELECT COUNT(*) n FROM workers WHERE scope='demo'").get().n,12);assert.equal(sql.prepare("SELECT COUNT(*) n FROM sites WHERE scope='demo'").get().n,4);const r=await api.state.GET(new Request('https://app.example.test/api/state?scope=live'));assert.equal(r.status,200);assert.equal((await r.json()).workers.length,0);});
test('retries save a payment exactly once; changed payload with the same key is rejected',async()=>{await setup();const b=pay();assert.equal((await call('payments',b)).status,200);const retry=await call('payments',b);assert.equal(retry.status,200);assert.equal(retry.data.replayed,true);assert.equal(sql.prepare('SELECT COUNT(*) n FROM payments WHERE id=?').get(b.operationId).n,1);assert.equal((await call('payments',{...b,amount:60000})).status,409);});
test('stale edits cannot overwrite the other phone and do not create an audit entry',async()=>{await setup();const b=op({workerId:'demo-worker-0',date:now,amSiteId:'demo-site-1',pmSiteId:null,version:1,reason:''});assert.equal((await call('attendance',b)).status,200);const stale={...b,operationId:crypto.randomUUID(),pmSiteId:'demo-site-1'};assert.equal((await call('attendance',stale)).status,409);const row=sql.prepare('SELECT * FROM attendance WHERE worker_id=? AND date=?').get(b.workerId,now);assert.equal(row.version,2);assert.equal(row.pm_site_id,null);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit WHERE id=?').get(stale.operationId).n,0);});
test('a first attendance record can be safely retried and cannot coexist with a second day record',async()=>{await setup();const b=op({workerId:'demo-worker-10',date:now,amSiteId:'demo-site-1',pmSiteId:'demo-site-2',version:0,reason:''});assert.equal((await call('attendance',b)).status,200);assert.equal((await call('attendance',b)).data.replayed,true);assert.equal(sql.prepare('SELECT COUNT(*) n FROM attendance WHERE worker_id=? AND date=?').get(b.workerId,now).n,1);assert.equal((await call('attendance',{...b,operationId:crypto.randomUUID()})).status,409);});
test('an attendance record cannot mix live and sample sites',async()=>{await setup();sql.prepare("INSERT INTO sites(id,scope,name,owner,address,color) VALUES('real-site','live','Real','Owner','Address','blue')").run();const r=await call('attendance',op({workerId:'demo-worker-0',date:now,amSiteId:'real-site',pmSiteId:null,version:1,reason:''}));assert.equal(r.status,400);});
test('reversal keeps the original, restores exactly its amount, and cannot be repeated',async()=>{await setup();const payment=pay();await call('payments',payment);const b=op({paymentId:payment.operationId,reason:'Duplicate entry'});assert.equal((await call('reversals',b)).status,200);assert.equal((await call('reversals',b)).data.replayed,true);assert.equal((await call('reversals',{...b,operationId:crypto.randomUUID()})).status,409);const entries=sql.prepare('SELECT amount,kind FROM payments WHERE id=? OR reversal_of=?').all(payment.operationId,payment.operationId);assert.equal(entries.length,2);assert.equal(entries.reduce((sum,p)=>sum+(p.kind==='reversal'?-p.amount:p.amount),0),0);});
test('operator can record today but cannot edit workers or backdate payments',async()=>{await setup();await call('members',op({email:'father@example.test',name:'Father',role:'operator',active:1}));context.who={id:'father',email:'father@example.test',name:'Father'};assert.equal((await call('payments',pay())).status,200);assert.equal((await call('workers',{})).status,403);assert.equal((await call('payments',{...pay(),date:'2026-01-01'})).status,403);});
test('server rejects future dates, zero amounts, fractional paise and cross-origin writes',async()=>{await setup();assert.equal((await call('payments',{...pay(),date:'2099-01-01'})).status,400);assert.equal((await call('payments',{...pay(),amount:0})).status,400);assert.equal((await call('payments',{...pay(),amount:1.5})).status,400);assert.equal((await call('payments',pay(),{origin:'https://untrusted.test'})).status,403);});
test('a revoked user immediately loses API access',async()=>{await setup();await call('members',op({email:'father@example.test',name:'Father',role:'operator',active:1}));context.who={id:'father',email:'father@example.test',name:'Father'};await call('payments',pay());context.who={id:'owner',email:'owner@example.test',name:'Owner'};await call('members',op({email:'father@example.test',name:'Father',role:'operator',active:0}));context.who={id:'father',email:'father@example.test',name:'Father'};assert.equal((await call('payments',pay())).status,403);});
test('failed database statements roll back payment and receipt together',async()=>{await setup();const b=pay();const original=context.DB.batch;context.DB.batch=async statements=>original([...statements,new Statement('INSERT INTO no_such_table VALUES (1)')]);const previous=console.error;console.error=()=>{};try{const result=await call('payments',b);assert.equal(result.status,503);assert.equal(sql.prepare('SELECT COUNT(*) n FROM payments WHERE id=?').get(b.operationId).n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit WHERE id=?').get(b.operationId).n,0);}finally{console.error=previous;context.DB.batch=original;}});

test('an invalid version for an unmarked day leaves no false absence behind',async()=>{await setup();const b=op({workerId:'demo-worker-10',date:now,amSiteId:'demo-site-1',pmSiteId:null,version:9,reason:''});assert.equal((await call('attendance',b)).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM attendance WHERE worker_id=? AND date=?').get(b.workerId,now).n,0);});
